### ISSUE TITLE
Unable to receive callback from oraclize on Rinkeby testnet

### ISSUE THREAD

**Issue by ishgoel** [oraclize/ethereum-api#14]
Hi,

We have developed a MVP on Rinkeby testnet and have used oraclize to access our APIs. It was working perfectly until yesterday, but somehow it is not working today. To dive deep into the problem, we created a sample contract on both Rinkeby and Ropsten networks. We got the desired results on Ropsten but somehow there seems to be no callback on Rinkeby. 

The issue is extremely urgent for us. Your kind help would be highly appreciated.

Please find below sample contract code:
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract YourContractName is usingOraclize {

    mapping(bytes32=>bool) public myidList;
    bytes32 public callapi;
    bytes32 public res;
    function YourContractName(){
        bytes32 myid=oraclize_query("URL","https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=BTC,USD,EUR,GBP");
        callapi=myid;
    }

    function __callback(bytes32 myid, string result) {
        if(msg.sender != oraclize_cbAddress()) throw;
        if(myidList[myid]==true) {
          // check if this myid was already processed before
          throw;
        }
        res=myid;
        myidList[myid] = true; // mark this myid (default bool value is false)
        
    }

}

**Comment by D-Nice** [comment]
Confirmed to have been fixed via gitter.
