### ISSUE TITLE
empty response from infura URL endpoint using POST payload

### ISSUE THREAD

**Issue by okwme** [oraclize/ethereum-api#16]
i'm using the Oraclize test query to confirm my oraclize response is empty. [Here's a link](http://app.oraclize.it/home/test_query#VVJMKFBPU1Qp:anNvbihodHRwczovL21haW5uZXQuaW5mdXJhLmlvLykucmVzdWx0:eyJqc29ucnBjIjoiMi4wIiwiaWQiOjEsIm1ldGhvZCI6ImV0aF9ibG9ja051bWJlciIsInBhcmFtcyI6W119) to the exact test query, which contains the following:

````
URL  ["json(https://mainnet.infura.io/).result","{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}"]
````

When this same endpoint is queried with the same POST params from Postman like [here](https://documenter.getpostman.com/view/2826444/infura/713fHG3) I get a correct response. Why isn't Oraclize returning a valid response?

**Comment by okwme** [comment]
(for the record this is a test endpoint, i know you can access the current block number from within solidity with `block.number`)

**Comment by bertani** [comment]
Hello @okwme . When sending a POST request using the URL datasource, you can choose to either use the second argument as query string or as POST payload. To use the former, you need to specify a JSON dictionary of key-value pairs. To use the latter one, the second argument needs to contain a whitespace (or a newline char) at the very beginning or at the end of it.

In your case, as you want to use JSON-RPC, the data has to be specified in the POST payload, so you will need to add a whitespace (for example) at the beginning, [like I did here](http://app.oraclize.it/home/test_query#VVJMKFBPU1Qp:anNvbihodHRwczovL21haW5uZXQuaW5mdXJhLmlvLykucmVzdWx0:IHsianNvbnJwYyI6IjIuMCIsImlkIjoxLCJtZXRob2QiOiJldGhfYmxvY2tOdW1iZXIiLCJwYXJhbXMiOltdfQ==).

I hope this helps!

**Comment by okwme** [comment]
Amazing! Thank you!
Can you point me to where this is mentioned in the documentation?

**Comment by marcogiglio** [comment]
It is mentioned [here](http://docs.oraclize.it/#ethereum-quick-start-simple-query) and [here](http://docs.oraclize.it/#data-sources-url). Since the problem has been resolved, I will close the issue :)
