### ISSUE TITLE
oraclize_query with encrypted API key no longer works

### ISSUE THREAD

**Issue by wanshun123** [oraclize/ethereum-api#20]
I have a contract which uses Oraclize and encrypts the API key used in the query (using https://github.com/oraclize/encrypted-queries). The oraclize_query worked fine until today (I changed no code). I found if I don't use the encrypted key it works as normal. Was anything changed in Oraclize? I am using rinkeby and ropsten testnets.

**Comment by D-Nice** [comment]
Hi @wanshun123 

Please ensure you're using a unique encrypted query per contract. Each contract needs to have a unique encrypted query, even if the underlying decrypted part is the same. There may have been some work done on the backend, which may have delayed the registration of the encrypted arg to a specific contract, and you may have been allowed to use the same encrypted part for multiple contracts. As mentioned, this is normally not the case, so ensure you generate a new one for each contract!

Please advise if your contract works with a new one!

**Comment by wanshun123** [comment]
I had used the same encrypted query for dozens of contracts (in testing on ropsten/rinkeby) without issue. I have tried generating a new encrypted query but it still fails. 

Here is a contract that works (API key not encrypted - the `randomInt` variable will be a random number between 1 and 5 after Oraclize is done):

```
pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract RandomTest is usingOraclize {

    uint256 public randomInt;
        
    uint public timesCalled;

    function RandomTest() {
        update();
    }

    function __callback(bytes32 myid, string result) {
        if (msg.sender != oraclize_cbAddress()) throw;
        randomInt = parseInt(result);
        timesCalled++;
        // update();
  }
  
    function update() payable {
 
        oraclize_query(3, "URL", "json(https://api.random.org/json-rpc/1/invoke).result.random.data.0", '\n{"jsonrpc":"2.0","method":"generateIntegers","params":{"apiKey":"cb27ec95-721d-48e1-a08e-f55b23f3e87d","n":1,"min":1,"max":5,"replacement":true,"base":10},"id":1}');    

    }

}
```

The same contract with the API key in `oraclize_query` encrypted fails (of course if testing this yourself you'd need to encrypt the API key "cb27ec95-721d-48e1-a08e-f55b23f3e87d" yourself and use your own encryption to verify):

```
pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract RandomTest is usingOraclize {

    uint256 public randomInt;
        
    uint public timesCalled;

    function RandomTest() {
        update();
    }

    function __callback(bytes32 myid, string result) {
        if (msg.sender != oraclize_cbAddress()) throw;
        randomInt = parseInt(result);
        timesCalled++;
        // update();
  }
  
    function update() payable {
 
               oraclize_query(3, "URL", "json(https://api.random.org/json-rpc/1/invoke).result.random.data.0", '\n{"jsonrpc":"2.0","method":"generateIntegers","params":{"apiKey":${[decrypt]BM+ZXnziqMginfcz2m2WW2evN2vydzBf7ricMIdIpZO6rirIlOrQ46QdIdGGqxLpLe1SZZyFJ8Q5YWgPBGNimsolGtWBksGdYBmpnvmRE6a5Fbj2t809txlRJSogLjuncpn7yJsTSLgL3PBG/gP7XggFRtFf},"n":1,"min":1,"max":5,"replacement":true,"base":10},"id":1}');
  

    }

}
```

I'm encrypting the API key the same way as before:

`python encrypted_queries_tools.py -e -p 044992e9473b7d90ca54d2886c7addd14a61109af202f1c95e218b0c99eb060c7134c4ae46345d0383ac996185762f04997d6fd6c393c86e4325c469741e64eca9 "cb27ec95-721d-48e1-a08e-f55b23f3e87d"`

**Comment by D-Nice** [comment]
If wanting to encrypt only a partial part of the post parameters, you need to use the *nested* datasource, to make use of the *decrypt* pseudo-datasource. If you wish to stick with URL, then you have to encrypt the whole POST parameter argument.

**Comment by D-Nice** [comment]
Here's approx the nested version of what you were sending:

```
pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract RandomTest is usingOraclize {

    uint256 public randomInt;
        
    uint public timesCalled;

    function RandomTest() {
        update();
    }

    function __callback(bytes32 myid, string result) {
        if (msg.sender != oraclize_cbAddress()) throw;
        randomInt = parseInt(result);
        timesCalled++;
        // update();
  }
  
    function update() payable {
 
        oraclize_query("nested", 
        "[URL] ['json(https://api.random.org/json-rpc/1/invoke).result.random.data.0', '\\n{\"jsonrpc\":\"2.0\",\"method\":\"generateIntegers\",\"params\":{\"apiKey\":\"${[decrypt] BC0g0vRNXBsncsjq5Yv4ZMiv7FvgnjfCKCyGhumP76fxZv+AiX6oZMVaFSy9ODnFBJ/kqZpLgcsYPfvZlIalwZ97LpJxMJ4AWib/mnfUunYLF6jZ0D0AKpQ2+4g1PdlJ4yh0W0qDHUdALsn2mEjAFqJRVmNw}\",\"n\":1,\"min\":1,\"max\":5,\"replacement\":true${[identity] \"}\"},\"id\":1${[identity] \"}\"}']");    

    }

}
```

Note, I encrypted `cb27ec95-721d-48e1-a08e-f55b23f3e87d` without the quotations. If I wanted to use quotations, I would've had to escape them, and remove the current escaped quotations around the decrypt parameter.

**Comment by wanshun123** [comment]
Entirely my fault - sorry for the time waste.
