### ISSUE TITLE
deprecation of throw syntax

### ISSUE THREAD

**Issue by adamyala** [oraclize/ethereum-api#29]
As of 0.4.10 `throw` has been deprecated in favor of `assert()`, `require()` and `revert()`. Would a PR to replace `throw` accordingly in the ethereum API be welcomed?

I'm new to Solidity so I didn't know if `throw` was being kept for backwards compatibility or another reason.

**Comment by adamyala** [comment]
Ah, my apologies. I was looking at the wrong file.

Cheers

**Comment by D-Nice** [comment]
It is indeed being kept for backwards compatibility for the whole 0.4 subversion. Our pre 0.5 api leverages the newer methods.
