### ISSUE TITLE
Oraclize not working on Kovan testnet

### ISSUE THREAD

**Issue by tech-somish** [oraclize/ethereum-api#30]
Hi, 
We have been using Oraclize on Kovan for quite some time. Off late, oraclize is not working on Kovan. We also tried to test it separately using the code provided in your documentation.
`pragma solidity ^0.4.11;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract ExampleContract is usingOraclize {

    string public EURGBP;
    event updatedPrice(string price);
    event newOraclizeQuery(string description);

    function ExampleContract() payable {
        updatePrice();
    }

    function __callback(bytes32 myid, string result) {
        if (msg.sender != oraclize_cbAddress()) throw;
        EURGBP = result;
        updatedPrice(result);
    }

    function updatePrice() payable {
        if (oraclize_getPrice("URL") > this.balance) {
            newOraclizeQuery("Oraclize query was NOT sent, please add some ETH to cover for the query fee");
        } else {
            newOraclizeQuery("Oraclize query was sent, standing by for the answer..");
            oraclize_query("URL", "json(http://api.fixer.io/latest?symbols=USD,GBP).rates.GBP");
        }
    }
}`

We get the log as "Oraclize query was sent, standing by for the answer.." in the transaction sent but do not receive the callback event. Can you please help.

**Comment by marcogiglio** [comment]
Hi @tech-somish, apologize for the inconvenient. The Kovan network was upgrade 4 days ago, but our Parity client was still on the old chain. I have upgraded it and now it should be working. Note that I have reset it, so you should redeploy the contract again to see it working. Let me know if the issue is solved

**Comment by tech-somish** [comment]
Thanks a bunch @marcogiglio.
