### ISSUE TITLE
Huge count of warnings on 0.4.18

### ISSUE THREAD

**Issue by quantum13** [oraclize/ethereum-api#31]
like
```
Warning: No visibility specified. Defaulting to "public".
Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
Warning: "sha3" has been deprecated in favour of "keccak256"
...
```

**Comment by D-Nice** [comment]
Yes, oraclizeAPI_0.4.sol is fully compliant with the 0.4 subversion, and at one of the later updates of that subversion they decided to make warnings very verbose and add many deprecations. 

If you wish to use the newer features and remove many of the warnings, you can use our 0.5 release candidate, oraclizeAPI_0.5.sol, which was targeted at 0.4.18 solc, and will be retargeted at 0.5 once released.
