### ISSUE TITLE
Scheduled/Delayed queries not returning any usable data

### ISSUE THREAD

**Issue by postables** [oraclize/ethereum-api#34]
I have the following contract (https://gist.github.com/postables/61a2e1e3ae4798af180863a19c2dbd70) which can successfully call the update() function, and have Oraclize return a call by calling the `__callback` function.

Update call (https://rinkeby.etherscan.io/tx/0x216714c5c01ca86ec9e0f995a14aa873a60381f9ba8e275f5a16bb698a451ba2)

`__callback` call (https://rinkeby.etherscan.io/tx/0xabfb5f79390700c332005cfb6f7905bf8ac47238ad2e64ff5990db95284191e7)

Unfortunately it doesn't seem like the `__callback` works properly as the `ethUSD` value on the contract doesn't get updated and remains at 0.

**Comment by marcogiglio** [comment]
Hi @postables, there is a mistake in your query format. The delay should be a uint.. if you pass it as a string, the engine will consider it as the datasource. So the correct one is:
bytes32 _id = oraclize_query(60, "URL", "json(https://api.coinmarketcap.com/v1/ticker/ethereum/?convert=USD).0.price_usd");

**Comment by postables** [comment]
Oi!!!!! I feel silly as all heck now thank you very much
