### ISSUE TITLE
Request : Adding oraclize to QTUM network/blockchain

### ISSUE THREAD

**Issue by Illasera** [oraclize/ethereum-api#37]
Request to add oraclize to the QTUM blockchain, They are working with EVM as well
using ERC20 but again, on QTUM blockchain, not Ethereum's, QTUM have their own blockchain known as mainnet.

You can deploy the same contract bytecode and API to their network the same way you would do with ethereum, also using the solidify compiler, But to deploy it , you need qtum core wallet.

(Of course, you may need some QTUM to gas the contract creation)

For more info : https://explorer.qtum.org/

https://qtum.org/en/

**Comment by D-Nice** [comment]
@Illasera we have synchronized a node to QTUM, but after looking into it more, it did not have the web3 support that was expected, instead only exposing a qweb3 library which isn't interchangeable with web3 from what I have seen.

**Comment by D-Nice** [comment]
We will close this for now, if someone has a need for this, +1 Illasera's post or leave a comment.

**Comment by D-Nice** [comment]
@7flash sure, it's licensed under the GNU AFFERO GENERAL PUBLIC LICENSE.

The bridge is what's used for some Ethereum testnets and also RSK, and we planned to integrate it with QTUM but ran into the above hurdle.
