### ISSUE TITLE
The computation data source does not support multi-stage builds

### ISSUE THREAD

**Issue by derekchiang** [oraclize/ethereum-api#44]
This is not an issue with the Ethereum API per se, so let me know if I should report it somewhere else.

Basically, I found out that the `computation` data source does not support the ["multi-stage builds"](https://docs.docker.com/develop/develop-images/multistage-build/) feature that has been available in Docker since 17.05.

If your Docker image uses multi-stage builds, the result passed to your `__callback` will be an empty string.

**Comment by D-Nice** [comment]
Yes, we use an earlier version, namely Docker 1.12.1, which is likely why that feature is unavailable. Will leave this open for now in case there is some great demand for either this feature or others that are not available in the used version.

**Comment by D-Nice** [comment]
If there is a need for this, please leave a comment. Closing for now.
