### ISSUE TITLE
Wrong default gas price in rinkeby

### ISSUE THREAD

**Issue by quantum13** [oraclize/ethereum-api#59]
> If no settings are specified, Oraclize will use the default values of 200,000 gas and 20 GWei. This last value is on the higher-end of the pricing spectrum right now, but it helps having faster confirmation times during network-wide congestions.

https://docs.oraclize.it/#ethereum-quick-start-custom-gas-limit-and-gas-price

But now in rinkeby callbacks are called with gasprice=1gwei

**Comment by D-Nice** [comment]
That statement moreso applies to mainnet I would say, but maybe @bertani can comment on this.
