### ISSUE TITLE
Kovan support

### ISSUE THREAD

**Issue by izqui** [oraclize/ethereum-api#6]
Is Oraclize supporting Kovan any time soon? 

Thanks

**Comment by bertani** [comment]
It does since Monday, but we forgot to update the public oraclizeAPI with the new connector details. Good call, thanks!

It is integrated now, so using the latest oraclizeAPI.sol will make it.
https://github.com/oraclize/ethereum-api/commit/a1db9b4a3c9fecee98d61ef1682d58b6d98ff5cf

**Comment by izqui** [comment]
That's great, thanks for the quick response :)
