### ISSUE TITLE
Issues with Ropsten/Rinkeby

### ISSUE THREAD

**Issue by rrubo** [oraclize/ethereum-api#60]
Is there any issues with the testnets? I am not receiving an Oraclize callback neither on Ropsten nor on Rinkeby.

**Comment by D-Nice** [comment]
Our monitoring tools haven't triggered any warnings and there appear to be callbacks happening on both networks. 

https://ropsten.etherscan.io/address/0xdc8f20170c0946accf9627b3eb1513cfd1c0499f
https://rinkeby.etherscan.io/address/0x854bd635fd4e8684a326664e0698c8fefae6dd97

When did your issues start, you could also try remix with our module in the browser to eliminate contract issues, as the networks do appear to be working fine: https://remix.oraclize.it/#plugintitle=Oraclize&pluginurl=https://remix-plugin.oraclize.it&gist=9817193e5b05206847ed1fcd1d16bd1d

**Comment by rrubo** [comment]
Thank you, it indeed was a temporary issue.
