### ISSUE TITLE
parseAddr does not parse address correctly

### ISSUE THREAD

**Issue by polybioz** [oraclize/ethereum-api#8]
Two cases of input string and invalid result address:

1.
```
0x00330479D8DEE9F4f75bdB998B4ea3f0bf5e6357
0x0033047D4c895d64f75C1299C24ea3F0BF5E6357
```
2.
```
0x8916a228C5C2b998Dec4Eed6ef19D1A1eD95F5D2
0x8916a22c3932b99C4EC85Ed6Ef1d451224996942
```

You can try calling convert method on this contract
https://kovan.etherscan.io/address/0x8916a228C5C2b998Dec4Eed6ef19D1A1eD95F5D2

**Comment by polybioz** [comment]
it is caused by uppercase characters, all lowercase address is parsed correctly

**Comment by bertani** [comment]
It was a known bug, thanks for submitting the PR, merging now!
